### ISSUE TITLE
Restruturação e correção de dados.

### ISSUE THREAD

**Issue by johnaopedro** [unb-mds/Gastos-DF-2024-02#90]
# Tarefa

**Descrição**: Reestruturar a página `tables.html` utilizando JSON e JavaScript, além de realizar alterações no `app.py` para integrar os dados.

### Detalhes

- **Responsável**: Artur Mendonça
- **Prazo**: 08/12/2024

### Critérios de Conclusão

- [x] A página `tables.html` foi reestruturada para carregar os dados a partir de um arquivo JSON.
- [x] O código JavaScript foi implementado corretamente para consumir o JSON e exibir os dados na tabela.
- [x] O `app.py` foi alterado para integrar os dados.
- [x] A página `tables.html` exibe as informações corretamente, sem erros, após a reestruturação.

### Notas

- Certifique-se de que o JSON esteja bem estruturado e que os dados sejam acessados corretamente no JavaScript.
- Verifique se o servidor Flask (`app.py`) está retornando o JSON de forma adequada.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the /tables route to return JSON data instead of rendering a template. Added a new route /get_table_data to serve the JSON data for the table.

You can review changes in this commit: https://github.com/mnmnk43434/unb-mds-Squad13-90/commit/a74d6d0800329bdfbe5d16f36b9e5e7cfdf3d781.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by johnaopedro** [comment]
A PR relacionada foi aceita e "Merged" no repositório.
